package dev.cnpe.ventescaposbe.reporting.application.dto.response

import dev.cnpe.ventescaposbe.currency.vo.Money
import io.swagger.v3.oas.annotations.media.Schema

@Schema(description = "Sales performance data for a single brand.")
data class BrandSalesReport(
    
    @Schema(description = "ID of the brand.")
    val brandId: Long,

    @Schema(description = "Name of the brand (fetched).")
    val brandName: String,

    @Schema(description = "Total quantity of items sold from this brand.")
    val quantitySold: Double,

    @Schema(description = "Total revenue generated by this brand.")
    val totalRevenue: Money
)