package dev.cnpe.ventescaposbe.reporting.application.dto.response

import dev.cnpe.ventescaposbe.currency.vo.Money
import org.eclipse.microprofile.openapi.annotations.media.Schema

@Schema(description = "Sales performance data for a single cashier.")
data class CashierSalesReport(

    @Schema(description = "User IdP ID of the cashier.")
    val userIdpId: String,

    @Schema(description = "Name of the cashier (fetched).")
    val cashierName: String?,

    @Schema(description = "Total number of orders processed by this cashier.")
    val totalOrders: Int,

    @Schema(description = "Total revenue generated by this cashier.")
    val totalRevenue: Money
)