package dev.cnpe.ventescaposbe.reporting.application.dto.response

import dev.cnpe.ventescaposbe.currency.vo.Money
import io.swagger.v3.oas.annotations.media.Schema

@Schema(description = "Sales performance data for a single category.")
data class CategorySalesReport(
    
    @Schema(description = "ID of the category.")
    val categoryId: Long,

    @Schema(description = "Name of the category (fetched).")
    val categoryName: String,

    @Schema(description = "Total quantity of items sold from this category.")
    val quantitySold: Double,

    @Schema(description = "Total revenue generated by this category.")
    val totalRevenue: Money
)