package dev.cnpe.ventescaposbe.reporting.application.dto.response

import dev.cnpe.ventescaposbe.currency.vo.Money
import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal

@Schema(description = "Revenue contribution of a single category.")
data class CategoryRevenueShare(

    @Schema(description = "ID of the category.")
    val categoryId: Long,

    @Schema(description = "Name of the category.")
    val categoryName: String,

    @Schema(description = "Total revenue generated by this category.")
    val totalRevenue: Money,

    @Schema(description = "Percentage of total revenue contributed by this category.", example = "25.5")
    val percentageOfTotal: BigDecimal
)