package dev.cnpe.ventescaposbe.reporting.application.dto.response

import com.fasterxml.jackson.annotation.JsonInclude
import dev.cnpe.ventescaposbe.currency.vo.Money
import io.swagger.v3.oas.annotations.media.Schema

@Schema(description = "Sales performance data for a single product.")
@JsonInclude(JsonInclude.Include.NON_NULL)
data class ProductSalesReport(

    @Schema(description = "ID of the product.")
    val productId: Long,

    @Schema(description = "Name of the product (snapshot from order or fetched).")
    val productName: String,

    @Schema(description = "SKU of the product, if available.")
    val sku: String?,

    @Schema(description = "Total quantity sold in the period.")
    val quantitySold: Double,

    @Schema(description = "Total revenue generated by this product (sum of final line item prices).")
    val totalRevenue: Money,

    @Schema(description = "Total discount applied specifically to this product across orders.")
    val totalDiscount: Money?
)