services:
  postgres:
    image: 'postgres:16.8-alpine'
    container_name: ventesca_postgres_dev
    environment:
      POSTGRES_USER: ${MASTER_DB_USERNAME:-ventesca_admin}
      POSTGRES_PASSWORD: ${MASTER_DB_PASSWORD:-ventesca_secret}
      POSTGRES_DB: ${POSTGRES_DB:-ventesca_master_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ventesca_network
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: [ 'start-dev' ]
    container_name: ventesca_keycloak_dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "${KEYCLOAK_PORT:-8180}:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - ventesca_network


volumes:
     postgres_data:
     keycloak_data:
      driver: local

networks:
  ventesca_network:
    driver: bridge