spring:
  application:
    name: ventesca-be-kotlin
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  liquibase:
    change-log: classpath:db/changelog/master-changelog-master.xml
    enabled: true
  jpa:
    open-in-view: false
  docker:
    compose:
      lifecycle-management: start_only
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

app:
  tenant:
    schema:
      auto-update-on-startup: true # false in prod ⚠
  business:
    limits:
      max-users-per-business: ${MAX_SELLERS_PER_BUSINESS:10}
      max-branches-per-business: ${MAX_BRANCHES_PER_BUSINESS:5}
  datasource:
    # Master Datasource
    master:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ventesca_master_db}
      username: ${MASTER_DB_USERNAME:ventesca_admin}
      password: ${MASTER_DB_PASSWORD:ventesca_secret}
      hikari:
        maximum-pool-size: 5
        pool-name: master-pool
    # Tenant Datasource Configuration
    tenant:
      url-template: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/ventesca_{tenant}_db
      username: ${MASTER_DB_USERNAME:ventesca_admin}
      password: ${MASTER_DB_PASSWORD:ventesca_secret}
      hikari: #
        maximum-pool-size: 10
        pool-name-prefix: tenant-pool-
  hibernate:
    debug: false

keycloak:
  admin:
    server-url: ${KEYCLOAK_URL:http://localhost:8180}
    realm: ${KEYCLOAK_ADMIN_REALM:master} #  'master' for admin operations, or app realm if service account used there
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
    username: ${KEYCLOAK_ADMIN_USERNAME:}
    password: ${KEYCLOAK_ADMIN_PASSWORD:}
    grant-type: client_credentials